### ISSUE TITLE
Add URI to search parameters

### ISSUE THREAD

**Issue by maxrom** [bitwarden/web#100]
> I opened this as browser extension issue 263 last night by mistake when this is actually a problem with vault.bitwarden.com.

I've imported my LastPass data and wanted to try something I found is already getting worked on in browser issue 77. Specifically, companies who use Taleo for job postings. So I'll have quite a few logins for  `company1.taleo.net`, `company2.taleo.net`, etc. which each have their distinct accounts. 

But I've found another problem entirely. If I search for `taleo` or `taleo.net`, the only results I got were those that had `taleo` in the name of the login. I usually just name them `Company1`, `Company2`, etc.

Curiously, this works as expected on logins I create with bitwarden itself. The only other example I can think of to test this phenomenon is my Microsoft account being named `Microsoft` but the login URI is `login.live.com`. A search for `live` doesn't bring that one up, but will bring up a bitwarden-created entry with a URI of `live.com` and name without `live`.

**Comment by meffect** [comment]
Check out [Equivalent Domains](https://blog.bitwarden.com/new-feature-equivalent-domains-dd29aa462bb7). Also those are URL's not URI's

**Comment by jpbaril** [comment]
The problem raised by maxrom has nothing to do with equivalent domains. But yeah, maxrom should remove the first two paragraphs of this issue as they are confusing and refer to issue 77.

As for the real issue at hand here, quite simply said, the web vault search feature only searches the name field of a site. It has to also search in the URI field. In the extensions the search feature correctly search in the two fields.

**Comment by kspearrin** [comment]
We are moving away from tracking Bitwarden feature requests like this one as GitHub issues. We have created a [Bitwarden Community Forum](https://community.bitwarden.com) which has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests). Please [sign up on our forums](https://community.bitwarden.com/signup) if you want to continue contributing to feature requests.

Since this was a popular feature request we have already re-created it on the forums and linked back to this GitHub issue for reference. You can vote for this feature request there if you'd like.

https://community.bitwarden.com/t/advanced-vault-searching/36

This issue will now be closed. Thanks!
