### ISSUE TITLE
Folders & Collections does not display

### ISSUE THREAD

**Issue by jboss38** [bitwarden/web#1117]
## Describe the Bug

When using Web (And Desktop) App, the folder and collection does not load. (Loading appear in infinite) 
The Chrome Extension (and mobile app) does not have this issue.

## Steps To Reproduce

Use Browser and desktop app with a lot of Folders and collections.

## Expected Result

Folders and collections should display correctly

## Actual Result

Loading fodler and collection in infinite...

## Screenshots or Videos

![BW not loading](https://user-images.githubusercontent.com/6693379/128691989-1fc91da7-dc49-463d-b951-e0c4e5c24fc5.PNG)

![error bt](https://user-images.githubusercontent.com/6693379/128692824-2cf413f3-4762-416b-9ef7-334e4e25236a.PNG)

## Environment

- Operating system: Windows 10
- Browser: Chrome up to date
- Build Version (Bottom of the page): [2.20.3]

## Additional Context

No issue when using with brand new browser.
Clearing cache does not fix this.
Reinstallation the browser fix this issue for a while, but the issue reappear with the time.

**Comment by eliykat** [comment]
Hi @jboss38, this is a known issue that was fixed in previous versions.

For the web vault: it looks like you're self-hosting - please upgrade your self-hosted instance to version 2.21.0 or later, clear your web browser cache, and the issue should be resolved.

For the desktop app: please update to version 1.26.4 or later. You'll also need to clear your local data either before or after the update. On Windows, local data is stored in the following location, depending on your install method:

* Standard Installation: %AppData%\Bitwarden
* Microsoft Store Installation: %LocalAppData%\Packages\8bitSolutionsLLC.bitwardendesktop_h4e712dmw3xyy\LocalCache\Roaming\Bitwarden
* Portable: .\bitwarden-appdata

([More info if required](https://bitwarden.com/help/article/data-storage/#on-your-local-machine))

If you have any trouble resolving the issue, please contact our customer success team [here](https://bitwarden.com/contact/) and they'll step you through the process. As the bug has already been fixed at this end, I'll close this issue.
