### ISSUE TITLE
[Suggestion] Add Shift & Ctrl Click When Bulk Selecting Items

### ISSUE THREAD

**Issue by pkkid** [bitwarden/web#116]
I found it quite tedious when I had to move 50 items into a folder and had to manually click each item. Shift and Ctrl click behavior would have been nice to multiselect them.

**Comment by kspearrin** [comment]
We are moving away from tracking Bitwarden feature requests like this one as GitHub issues. We have created a [Bitwarden Community Forum](https://community.bitwarden.com) which has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests).

Please [sign up on our forums](https://community.bitwarden.com/signup), search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
