### ISSUE TITLE
Email verification on self-hosted vault

### ISSUE THREAD

**Issue by Jonybat** [bitwarden/web#123]
Im giving this a go as a likely LastPass replacement, in the self hosted variant. One thing i noticed is that when i login to the vault, it asks me to verify my email, in this orange banner. Im assuming that this verification email is sent through the smtp server defined in the env file. 

So, would it be possible to have an option to disable the email verification on a self hosted env? I am aware that this would disable the 2 step email auth also, but without a valid server it doesnt work anyway.

Keep up the great work

**Comment by kspearrin** [comment]
We are moving away from tracking Bitwarden feature requests like this one as GitHub issues. We have created a [Bitwarden Community Forum](https://community.bitwarden.com) which has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests).

Please [sign up on our forums](https://community.bitwarden.com/signup), search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
