### ISSUE TITLE
Import cards and identities properly from 1Passoword

### ISSUE THREAD

**Issue by shishi** [bitwarden/web#128]
I tested import from 1Password, all my secure notes were imported as logins and not imported identities and credit cards.

I think It should import with their type correctly, or tell bitwarden can't import them.

**Comment by DidierLmn** [comment]
There also seems to be an issue with importing 'password' types from 1Password into Bitwarden.

(I don't know if it's the same issue, but it seems related that's why I report here instead of making a new issue)

The 'password' types get imported into Bitwarden, the name and custom fields are no problem either, HOWEVER, the actual 'password' isn't imported, it's just blank in Bitwarden.

**Comment by jonasschuele** [comment]
I had the same issue, the passwords were not imported for the "Password" types.

**Comment by kspearrin** [comment]
This is fixed in v2.0.0
