### ISSUE TITLE
Suggested Feature: Search includes folder name

### ISSUE THREAD

**Issue by calltheninja** [bitwarden/web#130]
It may be useful for some people to have the search bar also search folder names. For example, my password hierarchy is like this for storing passwords of clients:

Bob's Lawnmower Repair
-- router password
-- modem password

Jenna's Car Detailing
-- router password
-- modem password

So if I search for "router" it will show me both router passwords. If I search for "router jenna" it displays nothing because "jenna" isn't found in any password title, just the folder their organized under. Since most clients will have similarly-named passwords, the search list for "router" can get big quite quickly.

**Comment by kspearrin** [comment]
We are moving away from tracking Bitwarden feature requests like this one as GitHub issues. We have created a [Bitwarden Community Forum](https://community.bitwarden.com) which has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests). Please [sign up on our forums](https://community.bitwarden.com/signup) if you want to continue contributing to feature requests.

Since this was a popular feature request we have already re-created it on the forums and linked back to this GitHub issue for reference. You can vote for this feature request there if you'd like.

https://community.bitwarden.com/t/advanced-vault-searching/36

This issue will now be closed. Thanks!
