### ISSUE TITLE
Feature Request: Premium Family Plan

### ISSUE THREAD

**Issue by trparky** [bitwarden/web#136]
Right now the Family organization plan allows you to have the following features...

For personal use, to share with family & friends.
- Add and share with up to 5 users
- Create unlimited collections
- 1 GB encrypted file storage
- Self-hosting (optional)
- Priority customer support
- 7 day free trial, cancel anytime

But what would be nice is that maybe for 50 or 75 cents more per month each member of the family group gets access to the Premium features such as OTP key support for Logins.

**Comment by kspearrin** [comment]
We are moving away from tracking Bitwarden feature requests like this one as GitHub issues. We have created a [Bitwarden Community Forum](https://community.bitwarden.com) which has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests).

Please [sign up on our forums](https://community.bitwarden.com/signup), search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
