### ISSUE TITLE
UI not responsive

### ISSUE THREAD

**Issue by jdescelliers** [bitwarden/web#1362]
### Steps To Reproduce

4. Click on '...'

### Expected Result

Somewhat responsive UI when going to a mobile resolution (e.g. lower than 720px width.

### Actual Result

The UI isn't responsive as bootstrap columns aren't used.

### Additional Context

Since redesign proposals can't be decided by a single individual. Are you open to improvements to current layout? Like using CSS grid for example.

### Operating System

macOS

### Web Browser

Safari

### Browser Version

15.2

### Build Version

2.25.0

**Comment by Hinton** [comment]
Hi @jdescelliers,

We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one.

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
