### ISSUE TITLE
Removed folders and content are not in Trash, but in No Folder

### ISSUE THREAD

**Issue by MartinX3** [bitwarden/web#1476]
### Steps To Reproduce

1. Remove a folder with content
2. Look into the Trash
3. Look into the "No folders" folder

### Expected Result

The nested folder with content in the trash

### Actual Result

No folders anyway and all the content is in the "No Folders"-Folder, like a flatmap.

### Build Version

1.30

### Environment

Cloud (bitwarden.com)

**Comment by Hinton** [comment]
Hi @MartinX3, this is the expected behavior. Removing a folder only removes the representation of that folder, all ciphers within the folder does not get added to trash.

We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one.

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!

**Comment by MartinX3** [comment]
It's not a bug, it's a feature!™

**Comment by Hinton** [comment]
I understand the sentiment @MartinX3. It's documented on our help pages https://bitwarden.com/help/folders/.
