### ISSUE TITLE
Promote free software for 2FA

### ISSUE THREAD

**Issue by vhscom** [bitwarden/web#1483]
### Steps To Reproduce

1. Go to Web
2. Click on Two-step login
3. Scroll down to Providers
4. Click on Manage Authenticator App

### Expected Result

Free software such as [Aegis Authenticator](https://getaegis.app/) is promoted.

### Actual Result

Goolag and Authy only options shown 😦 

### Additional Context

Being free software yourself its important you push in the direction of promoting free software alternatives to commercial products such as Google Authenticator and Authy.

### Operating System

Linux

### Operating System Version

5 or something

### Web Browser

Safari

### Browser Version

97

### Build Version

N/a

**Comment by vhscom** [comment]
It would also be nice to help Pass users generate `otpauth` strings similar to how [oathqr](https://oathqr.vercel.app/) does it so they don't have to use yet another app when it's not necessary to generate OTPs.

**Comment by eliykat** [comment]
We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one.

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!

**Comment by vhscom** [comment]
I prefer not to create an account. Thanks for your understanding!

**Comment by vhscom** [comment]
I saw that. But I don't like Discourse as it doesn't give me enough control over my data. I hope you understand. Nevertheless the feedback has been giving. Cheers.
