### ISSUE TITLE
Skips bitwarden 2FA using windows password. 

### ISSUE THREAD

**Issue by prajwal-koirala-0000** [bitwarden/web#1580]
### Steps To Reproduce

Login to bitwarden vault from a windows system.
Chose webauth and than use windows password to skip 2fa

### Expected Result

To use the security key instead of the windows password. 

### Actual Result

I can use the windows password to skip bitwarden 2FA

### Screenshots or Videos

![Screenshot-2022-04-04-085211](https://user-images.githubusercontent.com/102563715/161548473-b4cd69c8-ed22-45d7-87df-5a5920af5318.png)

### Additional Context

Cleared browse cache and other things, reset the browser and still skips the 2FA using windows password.

### Operating System

Windows

### Operating System Version

11

### Web Browser

Chrome, Microsoft Edge

### Browser Version

100

### Build Version

2.27.0

**Comment by sso-bitwarden** [comment]
This is not a bug. It is because Windows Hello can be used as Webauthn as well. When you tried to register your key for the first time, browser will prompt to use Windows Hello first. If you want to register your physical key, you need to cancel the first prompt. 

You may want to log in and re-setup your Webauthn. Delete the current key, and try to register your physical key.

**Comment by tangowithfoxtrot** [comment]
As stated above, this is not a bug, and is something handled by Windows. Since the feature is working as intended, this issue will now be closed. Thanks!
