### ISSUE TITLE
The field Notes must be a string with a maximum length of 10000.

### ISSUE THREAD

**Issue by czb** [bitwarden/web#162]
Are there any plans on increasing the maximum length? I am importing everything from Lastpass but I cannot import one important note that has ca. 15 000 characters.

PS; The note is is a HTML file which is used to install a digital signature on a new PC.

**Comment by kspearrin** [comment]
No plans since this is what file attachments are for.

**Comment by czb** [comment]
Thanks for the prompt answer 👍  Did not notice this feature was available ;)

**Comment by watsoncj** [comment]
Consider mentioning attachments in the validation message about notes length.

**Comment by myfreeweb** [comment]
An option to just skip these long fields would be nice. Encountered this error, turns out I've had a copy of some old google terms of service (lol) in my 1password export, accidentally saved by a browser extension…

**Comment by idiotonuni** [comment]
On the importer It fails and states that
"An error has occurred.
Ciphers[346]: The field Notes exceeds the maximum encrypted value length of 10000 characters."

Maybe its a confusing name that I created, or maybe its not telling me which entry is over the 10000 character max. It would be very helpful to know which entry the importer choked on that was over 10000 characters.

**Comment by kspearrin** [comment]
> It would be very helpful to know which entry the importer choked on that was over 10000 characters.

Open the CSV file in a spreadsheet program. It's index 346

**Comment by myfreeweb** [comment]
@luvis hm — 1pif is lines of JSON, not CSV. Anyway, it's not necessarily notes, it can be any form field. I opened the 1pif file in a text editor and found a very very long line where 1password saved google terms of service as a form field

**Comment by luvis** [comment]
@idiotonuni @myfreeweb 
Thanks for your suggestions. I did followed your suggestions and eventually just removed any entry that was longer than a descently long url.. obviously not 10000 characters.. but I'm guessing the problem was in the 1password export on mac. I created a virtual machine solely for this and installed windows and the windows version of 1password only to export the passwords from there. Voila, no more issues and the import was fine. So if anyone else has problems with importing from 1password, hope it helps..

**Comment by flybyray** [comment]
> No plans since this is what file attachments are for.

But attachments are not imported at all see https://github.com/bitwarden/web/issues/183
Currently just 'String' entries are imported: https://github.com/bitwarden/jslib/blob/master/src/importers/keepass2XmlImporter.ts#L54

**Comment by jult** [comment]
Why is this 'closed' ? It's still there, I get no warning or explanation about why some field suddenly has some maximum character amount, it's just horrible BOFH coding this way. Really, nobody is served by this silly limitation. Just allow filed 'Notes' to be any amount. Seriously, NOBODY is damaged by it, except some of your FOSS egos, obviously. Ludicrously silly limitations. And by the way; everyone around me at home and at work encountered the same error, and therefore stopped trying to use bitwarden.

**Comment by Crocmagnon** [comment]
Hi there 👋 
Somebody is indeed damaged by this limitation: the Bitwarden team. The business model behind Bitwarden Premium includes encrypted file attachments. Notes are for small amounts of text, like a product license key for example.
A big "note" of more than 10'000 chars is likely an SSH key or a GPG key. If you use these, you're likely the target of the premium membership (which I found very reasonably priced, and I'm not affiliated with BW).
This limitation pushes you in the direction of buying the premium plan.

I do agree though that the error message is not clear and should be improved. Also, fields with more than 10'000 chars could automatically create a text file attachment for users with premium.

**Comment by mprasil** [comment]
@Crocmagnon I think the actual issue and reason for the limitation on the field is that these fields are synced to all clients on _every_ sync. This means that every time any client calls the `/api/sync` endpoint, the server sends all the data for every single password stored. Data transfer is one bottleneck here, the other is that this needs to be decrypted client side. This is already quite a pain - especially on mobile devices.

Attachments on the other hand are only downloaded and decrypted when you try to open them.

I like your suggestion about creating textfile attachment automatically. It is not very straightforward to implement as you'd have to do the import in multiple steps instead of one big json `POST` that is generated now. This comes with a ton of edge cases that are sometimes tricky due to the fact that everything is client-side encrypted and server usually does not have any information to do something more than dumb data storage service..

**Comment by gardner** [comment]
That is interesting. So, it is a full download instead of some sort of rsync style reconciliation protocol? Could the entries be hashed and timestamped to send a map of what needs to be synced instead of sending everything?

**Comment by mprasil** [comment]
I should  add that I have experience from working on 3rd party server, so take this with a grain of salt - it might have changed.

But yeah, the sync endpoint just respond with all the items the user has access to.

**Comment by tonymet** [comment]
why not skip the offending entry?
