### ISSUE TITLE
Theme of Bitwarden and Self - Hosted Bitwarden differ

### ISSUE THREAD

**Issue by msrv** [bitwarden/web#163]
I noticed that the default Bitwarden web vault uses a black/blue/white theme, which is very nice.

The self hosted version uses a blue/white theme, which is low in contrast and not as readable to me as the black/blue/white theme.

How can i edit the theme? If it is not possible, please allow to change it.

**Comment by kspearrin** [comment]
We are moving away from tracking Bitwarden feature requests like this one as GitHub issues. We have created a [Bitwarden Community Forum](https://community.bitwarden.com) which has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests).

Please [sign up on our forums](https://community.bitwarden.com/signup), search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
