### ISSUE TITLE
Export to encrypted KeePass file instead of unencrypted csv

### ISSUE THREAD

**Issue by CursingRabbit** [bitwarden/web#164]
Exporting currently saves the database as unencrypted csv.

It would be more secure to save it directly into an encrypted file, like KeePass' kdbx.

**Comment by kspearrin** [comment]
We plan to add encrypred export, but it isnt planned to be in kdbx format.

**Comment by kspearrin** [comment]
We are moving away from tracking Bitwarden feature requests like this one as GitHub issues. We have created a [Bitwarden Community Forum](https://community.bitwarden.com) which has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests). Please [sign up on our forums](https://community.bitwarden.com/signup) if you want to continue contributing to feature requests.

Since this was a popular feature request we have already re-created it on the forums and linked back to this GitHub issue for reference. You can vote for this feature request there if you'd like.

https://community.bitwarden.com/t/encrypted-export/235

This issue will now be closed. Thanks!
