### ISSUE TITLE
Colorize passwords when viewing

### ISSUE THREAD

**Issue by navdpsingh** [bitwarden/web#165]
Feature request to colorize passwords when viewing them so that digits show up as another visible color (red for example) in order to differentiate characters/digits like "1" and "l", "O" and "0", etc.

**Comment by amenk** [comment]
Why not using a font which makes it clearly distinguishable? Actually it is already I would supposed ...

**Comment by navdpsingh** [comment]
Few thoughts after comparing it to my experiences using LastPass which used colorization:
- Colorization as compared to fonts is a faster way to visually distinguish them.
- Fonts can be tied to (at least on Android) an overall theme so keeping this as an app setting or feature separates it from any other visual customizations on a given phone.
- Colors work across both web and app versions of BitWarden.

**Comment by bts0004** [comment]
I would really like to see this enhancement as well. I never would have thought it was a big deal, but made a big difference for me when LastPass added it. When I switched over to bitwarden, it's definitely been missed.

**Comment by kspearrin** [comment]
We are moving away from tracking Bitwarden feature requests like this one as GitHub issues. We have created a [Bitwarden Community Forum](https://community.bitwarden.com) which has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests). Please [sign up on our forums](https://community.bitwarden.com/signup) if you want to continue contributing to feature requests.

Since this was a popular feature request we have already re-created it on the forums and linked back to this GitHub issue for reference. You can vote for this feature request there if you'd like.

https://community.bitwarden.com/t/color-code-password-display/236

This issue will now be closed. Thanks!
