### ISSUE TITLE
Firefox extenstion keeps logging out

### ISSUE THREAD

**Issue by pavankjadda** [bitwarden/web#1682]
### Steps To Reproduce

1. Go to Firefox and click on BW Extension
2. After logging in and the extension logs out

### Expected Result

The extension shouldn't logout

### Actual Result

The extension logs out

### Operating System

macOS

### Web Browser

Firefox

### Browser Version

100

### Build Version

Version: 1.58.0

**Comment by aj-bw** [comment]
Hi @pavankjadda!

Thank you for getting in touch and bringing this to our attention! So far, I have not been able to reproduce this issue. However, we would like to assist you further. We ask that you please contact us using our contact page, here: <https://bitwarden.com/contact.> You can include a link to this issue in the message content. The issue here will be closed and moved over to our Help Desk.
