### ISSUE TITLE
Credit card default fields are not hidden or no option for toggle

### ISSUE THREAD

**Issue by ajithijk** [bitwarden/web#173]
The credit card fields like Number, brand , expiration and security code need to have a hidden/toggle option to make it hidden by default or if that is what user needed for privacy. If using the browser extension or webvault or mobile app, there is always a risk of opening the credit card details and everyone who is looking into the screen can see all the critical info.

**Comment by kspearrin** [comment]
We are moving away from tracking Bitwarden feature requests like this one as GitHub issues. We have created a [Bitwarden Community Forum](https://community.bitwarden.com) which has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests).

Please [sign up on our forums](https://community.bitwarden.com/signup), search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
