### ISSUE TITLE
TOTP allow editable digital count and time

### ISSUE THREAD

**Issue by idnovic** [bitwarden/web#176]
Add support for 7 char TOTP codes on a 10 sec interval.
This is used by authy.

here is a writeup on that matter
https://randomoracle.wordpress.com/2017/02/15/extracting-otp-seeds-from-authy/

here how to import authy codes to an other generator
https://gist.github.com/JacobJohansen/5f688d45049be440b8ee87cc5e854b75

 tl;dr

Just allow to set the char count and time interval of the generated codes.
If an user wants to import keys from authy they are on their own.

**Comment by idnovic** [comment]
and add the same function to the non web clients

**Comment by kspearrin** [comment]
We are moving away from tracking Bitwarden feature requests like this one as GitHub issues. We have created a [Bitwarden Community Forum](https://community.bitwarden.com) which has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests).

Please [sign up on our forums](https://community.bitwarden.com/signup), search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
