### ISSUE TITLE
Please allow viewing registered users for self hosted installation

### ISSUE THREAD

**Issue by arjones85** [bitwarden/web#178]
... and possibly be able to administer them in some way, such as removing them.

Thanks!

**Comment by kspearrin** [comment]
a sys-admin dashboard is planned

**Comment by arjones85** [comment]
That's going to be great! Thank you!

**Comment by kspearrin** [comment]
We are moving away from tracking Bitwarden feature requests like this one as GitHub issues. We have created a [Bitwarden Community Forum](https://community.bitwarden.com) which has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests). Please [sign up on our forums](https://community.bitwarden.com/signup) if you want to continue contributing to feature requests.

Since this was a popular feature request we have already re-created it on the forums and linked back to this GitHub issue for reference. You can vote for this feature request there if you'd like.

https://community.bitwarden.com/t/system-administrator-portal/196

This issue will now be closed. Thanks!
