### ISSUE TITLE
Import into specific folder

### ISSUE THREAD

**Issue by faxe78** [bitwarden/web#179]
Hi,

I have different vaults at 1password, so i would to keep the sorting in bitwarden. I think the best way would be to allow to define a target folder during the import process.

Thx

Markus

**Comment by kspearrin** [comment]
We are moving away from tracking Bitwarden feature requests like this one as GitHub issues. We have created a [Bitwarden Community Forum](https://community.bitwarden.com) which has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests).

Please [sign up on our forums](https://community.bitwarden.com/signup), search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
