### ISSUE TITLE
Duplicate an Entry

### ISSUE THREAD

**Issue by bradlis7** [bitwarden/web#180]
Can we have an additional action on entries to duplicate the record? Sometimes in development, I need to have multiple accounts, but will have the same URL, or I have the same username and the URL is slightly modified, so I want to make minor changes.

**Comment by kspearrin** [comment]
We are moving away from tracking Bitwarden feature requests like this one as GitHub issues. We have created a [Bitwarden Community Forum](https://community.bitwarden.com) which has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests). Please [sign up on our forums](https://community.bitwarden.com/signup) if you want to continue contributing to feature requests.

Since this was a popular feature request we have already re-created it on the forums and linked back to this GitHub issue for reference. You can vote for this feature request there if you'd like.

https://community.bitwarden.com/t/duplicate-an-existing-item-in-vault/150

This issue will now be closed. Thanks!
