### ISSUE TITLE
Avoid loading Stipe and Braintree before they’re needed

### ISSUE THREAD

**Issue by da2x** [bitwarden/web#187]
Stripe and Braintree injects scripts without Subresource Integrity checks on every page in the vault. ([More details](https://www.ctrl.blog/entry/migrating-to-bitwarden).)

To reduce the potential impact of these resources being modified/hijacked, they should only be loaded dynamically when the user visits `/#/settings/premium` instead of always including them when users are only visiting their vaults or other non-payment related pages. This would also shave 116 KB of vault page loads.

 Ideally, they should only be loaded on a separate page outside the main vault on a separate domain for performing payments.

**Comment by indolering** [comment]
The payments page should be moved to a distinct subdomain and loaded in via an iFrame.  User/session information can be passed in using PostMessage or via cookies.

**Comment by ahmedalsudani** [comment]
I agree with both of the previous comments. External resources are the only thing preventing me from switching to Bitwarden right now.

It would also be great if you could rely on your own CDN since that would allow me to limit outgoing connections to `vault.bitwarden.com` and `cdn.bitwarden.com`. It's possible to do that with 1password by limiting outgoing connections to 3 domains controlled by AgileBits.

**Comment by kspearrin** [comment]
Fixed in v2.0. They are only loaded on payment pages now.
