### ISSUE TITLE
Merge vault items option 

### ISSUE THREAD

**Issue by piejanssens** [bitwarden/web#271]
This is the next big thing after your AWESOME multi URI support. 

Select vault items and 'Merge'. All these items will be merged into one and their URI's rules will be combined. User needs to select item of which the username/password should be copied.

**Comment by kspearrin** [comment]
We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one.

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
