### ISSUE TITLE
Add friendly names for language options

### ISSUE THREAD

**Issue by harogaston** [bitwarden/web#293]
https://github.com/bitwarden/web/blob/6f3074536a1ba57f385f32514a3ebc19e270be6d/src/services/i18n.service.ts#L13-L16

**Comment by kspearrin** [comment]
We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one.

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
