### ISSUE TITLE
"Logged in as" should display email address, not just name

### ISSUE THREAD

**Issue by jikquantopian** [bitwarden/web#304]
I have separate work and personal Bitwarden accounts. I sometimes have to switch between them. I can't easily tell which one I'm logged into because the "Logged in as" that shows up when I click on the little person icon just has my name, which is the same for both accounts. It should display the email address too.

**Comment by kspearrin** [comment]
We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one.

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
