### ISSUE TITLE
Ability to delete folder containing sites

### ISSUE THREAD

**Issue by ysshah** [bitwarden/web#33]
Not sure how easy this would be to implement, but having the option to delete a folder (and all the sites inside of it) would be appreciated. Instead, I have to manually delete every single site in the folder before deleting the folder.

**Comment by kspearrin** [comment]
Ill put this on the good idea backlist. Thanks.

**Comment by kspearrin** [comment]
We are moving away from tracking Bitwarden feature requests like this one as GitHub issues. We have created a [Bitwarden Community Forum](https://community.bitwarden.com) which has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests).

Please [sign up on our forums](https://community.bitwarden.com/signup), search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
