### ISSUE TITLE
Possible to create collections with the same name

### ISSUE THREAD

**Issue by jikquantopian** [bitwarden/web#332]
Apparently there's nothing preventing me from creating two collections with the exact same name; I just did this in the web console and it happily let me create the duplicate collection. Pretty sure this shouldn't be allowed.

**Comment by rugglcon** [comment]
Is this a thing that we want prevented? if so I could pick it up.

**Comment by UnicornInReverse** [comment]
I came across this today. When I import passwords under a collection "Example" they all appear under that collection, so far so good. When I ran another import with passwords with the collection "Example" a new collection had been created with the new passwords. Expected behaviour (for me at least) is that passwords from the new import will appear under the collection with the same name instead of creating a new one.

**Comment by sov-j** [comment]
This is still actual on Bitwarden.com web version 2.15.1 - just tested and I can create two collections with the same name (in both Chrome and Firefox if that matters).

**Comment by cscharf** [comment]
This is currently expected behavior, as far as items in your vault and collections, etc. may all have duplicate names. Items in Bitwarden are stored and indexed by GUIDs/UUIDs and therefore can handle or support duplicate names as a feature. Now, it can be argued both ways for probably years until distant aliens come down and settle the argument with ray guns, but ultimately if there's a specific issue or use-case in this behavior that you're experiencing, like what @UnicornInReverse has posted above then that's a different story with explicit expectations that we can work with. Keep in mind that large organizations may have multiple teams with various needs for collections, some of which may be duplicative, yet permissions separate different groups from those collections so the "Corporate Credit Cards" collection shared with Sales and Marketing Leadership is not the same "Corporate Credit Cards" collection shared with IT, Network and Operations Leadership, etc.

Are there any specific use-cases you're trying to accomplish that Bitwarden allowing duplicate collection names is causing issues with?

**Comment by dipakparmar** [comment]
@cscharf I'm trying to utilize the collections for multi-org, for example, org a has a marketing collection and org b also has a marketing collection.

so, looking at the personal/my vault page it now shows two marketing collection which is hard to filter. 

This was a simple example, we do have 300 orgs which has similar collections. A possible solution I'm thinking of is having an extra parent collection id and based on that having a tree view?

**Comment by cscharf** [comment]
Hi @dipakparmar , sorry for the late follow up, I'm looping in our product team on this. I don't believe we'll address duplicate names as this ticket identifies, but I know we have a card on our backlog/board in regards to the display of collections, items, and the organization of collections/items relating to Organizations. Not sure when we're projecting to tackle it, but it's definitely on there.

**Comment by ginat** [comment]
@dipakparmar thanks for flagging this! We are looking at how to handle collections/items/groups more holistically so appreciate the feedback. By the way, we will have a new product release in the coming weeks that will make administering multiple organizations a lot easier for our MSP customers. If you can send me a note at gtran@bitwarden.com, we'd be happy to provide a walkthrough and get you onboarded!

**Comment by dipakparmar** [comment]
> Hi @dipakparmar , sorry for the late follow up, I'm looping in our product team on this. I don't believe we'll address duplicate names as this ticket identifies, but I know we have a card on our backlog/board in regards to the display of collections, items, and the organization of collections/items relating to Organizations. Not sure when we're projecting to tackle it, but it's definitely on there.

Gald to hear that it's in the pipeline @cscharf! If you don't mind can you share the road map link if it is available publicly?

**Comment by dipakparmar** [comment]
> @dipakparmar thanks for flagging this! We are looking at how to handle collections/items/groups more holistically so appreciate the feedback. By the way, we will have a new product release in the coming weeks that will make administering multiple organizations a lot easier for our MSP customers. If you can send me a note at [gtran@bitwarden.com](mailto:gtran@bitwarden.com), we'd be happy to provide a walkthrough and get you onboarded!

Sure! Will drop an email. Thanks for the insights. :)

**Comment by jikamens** [comment]
This is still a bug.

**Comment by dwbit** [comment]
Hey everyone, since this is a discussion item and Bitwarden is currently functioning as expected (with a UI refresh on the way), future responses can be added to the [community forums](https://community.bitwarden.com/t/name-enforcement-duplicate-folders-or-collections/2122) post for review.
