### ISSUE TITLE
import from 1pif from 1 password via Web register duplicate info and/or not the rightkind of data

### ISSUE THREAD

**Issue by boistordu** [bitwarden/web#346]
I didn't try with other password manager nor did I investigate the 1pif file.

But apparently there are some quirks when importing from 1password.
When it's not a website which is imported but an item like server access, it will duplicate the password field, one as a good masked password field and a duplicate unmask as text.

When it's a website, if there is multiple password field, it will make one as password field then the others as unmasked text. Same behavior for server access too, in addition to the previous behavior.

Is this intended?

**Comment by kspearrin** [comment]
Bitwarden only supports 1 password field. If there are additional fields, they are mapped to custom fields. At this time, all custom fields are set as type "text" when importing.

**Comment by tobias--** [comment]
1Password keeps deleted entries in a trash folder. Entries from this folder also get imported without any hint adding to the confusion.

**Comment by djsmith85** [comment]
Closing this as the importer has improved since then.
For example:
- Custom-fields that are marked as concealed by 1password are set to hidden. 
- Custom fields also handle the type `date`
- Trashed items are not longer imported

Also as 1Password is moving away from `.1pif` in favour of .`1pux` - we've started work on an importer for the new format at https://github.com/bitwarden/jslib/pull/594
