### ISSUE TITLE
Disable Website Icons state not remembered between sessions

### ISSUE THREAD

**Issue by setyb** [bitwarden/web#352]
Pretty simple to explain: The state of the `Disable Website Icons` does not seem to be maintained between web vault sessions.

TBH, I only tested it once, but I need to allocate my time to multiple projects.  I hope you understand.

What I did:
 1. Logged in to web vault (unchecking the "remember email" checkbox)
 2. Checked the `Disable Website Icons` option
 3. Logged out of web vault
 4. Cleared all caches
 5. Logged in to web vault (unchecking the "remember email" checkbox)
 6. Noticed that `Disable Website Icons` is now unchecked

**Comment by kspearrin** [comment]
This setting is saved in local storage in the browser. If that is cleared, the setting (and others) will be lost.

**Comment by setyb** [comment]
Would it be feasible to store the web vault settings in the vault?  That way, if you log in from another machine (or after clearing caches), settings will not be lost.

If you choose to do this, I think it would just be for the web vault.  Each browser extension can store their own settings locally.

**Comment by kspearrin** [comment]
Perhaps. Sounds like a feature request.

**Comment by setyb** [comment]
Definitely in that gray area between bug and feature request.  It looks like a bug (not retaining settings), but is actually doing what it is programmed to do (feature request).

**Comment by dustindauncey** [comment]
> Definitely in that gray area between bug and feature request. It looks like a bug (not retaining settings), but is actually doing what it is programmed to do (feature request).

I do not feel this is a bug, because it's working for everyone who doesn't have software or browsers configured to clear cache/storage on exit or startup. This is likely happening to you because you have a third-party program or setting in your browser which clears this data likely upon exit of the web browser. If that is not something you need, simply change the configuration so that these types of settings are preserved. Many browser plugins use local storage for these settings, and due to API restrictions are generally restricted to where they can stored.

**Comment by setyb** [comment]
@dustindauncey Thanks for your thoughts on it.

It goes beyond an individual device.  When the user logs in from another device (or even a different browser), their bitwarden web vault loses some of its settings.  This is a particular concern for the website icons setting, as *some* may consider it to be a security/privacy issue (which is why there is an option to disable it).

Let's compare this to just about every other web service available.  When you change a setting in other web services, those settings are retained between sessions, regardless of what computer or browser you log in from, or what you do with your computer.

Take for example the most popular web service in use today, web-based email.  Users configure their web-based email to how they like it, and when they log in from another computer or browser, all settings are retained.

**Comment by dustindauncey** [comment]
>@dustindauncey Thanks for your thoughts on it. ...

@setyb I could be wrong but these things can really only be stored at either the account level or client level. If account level, it’d be system wide and affect all Bitwarden client applications (unless there’s a way around that, which I’m not personally familiar with). If client level, it’d be a preference per client (the way it is designed now where client settings are stored on-device). 

I personally prefer the per client behaviour, as I like to disable showing cards on my work PC in the Bitwarden browser extension while wanting cards to show up on my personal computer. 

However, it’s an interesting point raised about the settings being lost for the web vault when logging in on a different browser or computer. That would indeed suggest this should be a feature that’s stored stateful within the web vault application instead of the client device. Maybe there should be a mix of per account settings or per device settings if this feature were to be implemented, or possibly even just having the option of syncing preferences or leaving per device.

**Comment by setyb** [comment]
@dustindauncey I agree with most of what you wrote, including some of your personal preferences.

As far as whether this is a feature request or bug, I think that's mostly a semantic thing.  GitHub calls everything "issues" to get around that discussion, but Kyle has chosen to separate feature requests on his discourse site and have bug reports here.  Wherever he wants to place this issue is fine by me.  Either he'll choose to implement something along the lines of what we discussed, or he won't. :)

The path of least resistance is to keep the issue here, but if it's not a good match, it can surely be moved to discourse with little effort.  I think your posts here have added additional value.

No matter what, I think we've both given him good feedback about the issue and some of the possible options to address it.

@kspearrin Feel free to ask any questions you have of either one of us regarding this issue, if you desire any additional feedback.
