### ISSUE TITLE
Cannot import Lastpass CSV due to max password encrypted value length

### ISSUE THREAD

**Issue by hilyin** [bitwarden/web#387]
The error I am getting when trying to import from lastpass csv is:

`
An error has occurred.
Ciphers[470].Login: The field Password exceeds the maximum encrypted value length of 1000 characters.
`

I go to line 470 of my csv file and it has a 15 character password.

**Comment by kspearrin** [comment]
470 is the index, not the line. There is also a header row. Rows can also take up multiple lines. I recommend opening the CSV in a spreadsheet program like Excel and locating row 472.

**Comment by hilyin** [comment]
@kspearrin thank you, that solved it.

**Comment by jult** [comment]
Except for many this means opening the spreadsheet and editing a LP exported csv for literally hours, and testing import for hours. Why punish yourself with these silly limitations?

**Comment by kachkaev** [comment]
Got the same cryptic error while importing my passwords from a LastPass CSV:

```
The field Password exceeds the maximum encrypted value length of 1000 characters.
```

Import is one of the most critical user stories in any project, yet my experience was pretty frustrating today. Because I had a mix of passwords and notes in LP CSV, I thought the issues is in #194 and ended up trying hacks like https://github.com/bitwarden/web/issues/194#issuecomment-464468578 for about an hour with no luck.

It turned out that the record to blame was a password to a kubernetes (k8s) dashboard. After I manually removed a corresponding line from a CSV, I could import my data successfully.

Ironically, the length of that problematic long password is under 1000 symbols. When I open `node` and type `"myToken".length`, I get 960, which is less than 1000. All chars are the ASCII ones, which suggests that password length calculation in Bitwarden is broken. Sadly, I cannot add this password to the password field of a card, so it has to stay in notes until I change my k8s dashboard token or until Bitwarden fixes this bug 😞

**Comment by jult** [comment]
A similar 'solution' for me, I had to remove a few LP Secure Notes, where apparently 1 had something in it that bitwarden would not accept. Narrowing it down to what is at fault would be too much work for me, so I decided to go the insecure route and exported all from LP in readable format, keep that in a safe place and just manually re-enter whenever something I miss in bitwarden is needed.
Must say I tried running my own bitwarden docker instance serving the password-db, but that too is not that well documented, so in the end I gave up. The bitwarden crew is better at advertising and appearances than at documenting examples and fixing bugs.
