### ISSUE TITLE
Lastpass CSV Import Bug

### ISSUE THREAD

**Issue by flawiddsouza** [bitwarden/web#40]
When I use the export option from Lastpass, this is the output I get:
```
url,username,password,extra,name,grouping,fav
https://somesite.com/#/,someusername,G%W!7&amp;#,,bitwarden.com,,0
```

bitwarden currently imports this output as is.

The problem is the password:
Exported: `G%W!7&amp;#`
Imported: `G%W!7&amp;#`
Actual password: `G%W!7&#`

It's the `&amp;`

It broke 200 of my logins that were imported from Lastpass. I had to use search and replace to fix this.

**Comment by kspearrin** [comment]
This is a LastPass bug, not bitwarden. How am I to know that a users password wasn't actually `G%W!7&amp;#`?

**Comment by King-Tut-Tut** [comment]
Yeah, they need to update their exporter.

**Comment by flawiddsouza** [comment]
Maybe add a line in the guide to warn users importing from Lastpass?

**Comment by kspearrin** [comment]
Looks like it only happens when exporting from their chrome extension: https://discussions.agilebits.com/discussion/59095/problem-with-ampersand-characters-in-import

**Comment by King-Tut-Tut** [comment]
Yeah, I'd just add a line in the help center telling people to avoid exporting from Chrome until it has been fixed (assuming it only happens from the Chrome extension/web extensions).

**Comment by flawiddsouza** [comment]
@King-Tut-Tut Yup.

**Comment by mkuhring** [comment]
I just switched from LastPass as well (this bug was actually another good reason to do so). Anyways, I had the same issue using their export function in Firefox. But doing a search and replace doesn't seem to be a 100% safe options when having a lot of passwords. So I looked into the other LastPass tools and found [Pocket](https://lastpass.com/misc_download2.php) (available for Windows and Linux, though on Linux I ran into library incompatibilities). Not sure whether it is still supported. But at least the export function doesn't seem to have this error (I just checked for a few passwords thought).

**Comment by davebrny** [comment]
that bug is still present in their chrome extension. everything is ok when exporting from their website as far as i can tell. 
still though, its been a year and a half and no fix. bad form. what are lastpass doing with all that money i sent them!?
