### ISSUE TITLE
Storing recovery codes

### ISSUE THREAD

**Issue by lucmos** [bitwarden/web#412]
Many websites offer one-time recovery codes in case the second factor is lost/inaccessible.

Example of GitHub recovery codes format:
```
xxxxx-xxxxx 
xxxxx-xxxxx 
xxxxx-xxxxx 
xxxxx-xxxxx 
xxxxx-xxxxx 
xxxxx-xxxxx 
xxxxx-xxxxx 
xxxxx-xxxxx 
xxxxx-xxxxx 
xxxxx-xxxxx 
xxxxx-xxxxx 
xxxxx-xxxxx 
xxxxx-xxxxx 
xxxxx-xxxxx 
xxxxx-xxxxx 
xxxxx-xxxxx
```

Similar codes are released by Google and many others.

I want to store those recovery codes in bitwarden.
I can see two possible places:

* Custom fields
* Notes

However inserting each code in a custom field is extremely tedious and error prone (you can't copy paste the whole block).
e.g.
![image](https://user-images.githubusercontent.com/11019190/65840114-10f7bb80-e315-11e9-8b64-b6081fb3197b.png)

Meanwhile the Notes can't be hidden, so it is a privacy concern if someone looks at the screen while you are copying the password.

I'd like something to address this problem.

The possible solutions that I can think of are:
* A button to hide the Notes
* Default to Notes to hidden mode and add the eye button
* Another field  "Hidden notes"
* Easier compilation of custom fields (inserting a value with a new line creates a new one?)

**Comment by kspearrin** [comment]
Thanks for the feedback. Currently, I just use notes for this type of stuff, but I don't really have a concern for someone shoulder surfing my notes.

**Comment by woble** [comment]
Is there a reason multi-line custom field is not a thing?

**Comment by MartinX3** [comment]
Still an open issue with 1.31.2

**Comment by Hinton** [comment]
We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one.

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
