### ISSUE TITLE
Cannot use platform keys for WebAuthn

### ISSUE THREAD

**Issue by Bodup** [bitwarden/web#424]
When adding security keys, bitwarden only allows the user to use cross-platform keys (e.g USB keys such as yubikeys) and therefore the user is prevented from choosing something like Windows Hello or Touch ID on MacOS. 
This should perhaps be changed to match the behavior of [WebAuthn.io](https://webauthn.io/) with 'unspecified' as the authenticator type.

**Comment by Bodup** [comment]
It seems that bitwarden doesn't implement WebAuthn yet. It still uses U2F.
So this issue can't be resolved until that changes.

**Comment by kspearrin** [comment]
We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one.

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!

**Comment by beerisgood** [comment]
Just as notice, it exist a feature request on official forum:
https://community.bitwarden.com/t/update-fido-u2f-to-webauthn/3308
