### ISSUE TITLE
Determine if Bitwarden could have been affected by Cloudflare leak

### ISSUE THREAD

**Issue by dgriffen** [bitwarden/web#43]
Cloudflare was recently disclosed to have been leaking information from HTTPS sessions. Since Bitwarden uses cloudflare it would be a good idea to determine if user data (master passwords, vault data) could have leaked to the outside world.

See [here](https://bugs.chromium.org/p/project-zero/issues/detail?id=1139) and [here](https://blog.cloudflare.com/incident-report-on-memory-leak-caused-by-cloudflare-parser-bug/) for posts on the leak.

**Comment by kspearrin** [comment]
I've been following this today. Thanks for bringing it up. At this time there is no reason to believe that bitwarden users have been negatively affected by this.

Your vault data is securely encrypted on your local machine before ever being transmitted over the internet. So even if it were leaked due to a TLS/SSL failure, MITM attack, compromised server, or anything of the like it is not at risk. More can be read here: https://help.bitwarden.com/security/

Obviously as more information comes to light in the coming days we'll learn more, but for now we're not recommending any action for users to take.

**Comment by kspearrin** [comment]
No evidence has come to light that changes anything from our original statements.
