### ISSUE TITLE
[Suggestion] Give warning when a user close the edit login window

### ISSUE THREAD

**Issue by yureiita** [bitwarden/web#44]
When adding a new login or edting a login, if a user made any changes in the fields, give a warning to prevent accidental closing of edit window.
![discard changes](https://cloud.githubusercontent.com/assets/26035759/23337774/5ab703d2-fc33-11e6-9550-30a6eacd5205.png)

**Comment by kspearrin** [comment]
We are moving away from tracking Bitwarden feature requests like this one as GitHub issues. We have created a [Bitwarden Community Forum](https://community.bitwarden.com) which has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests).

Please [sign up on our forums](https://community.bitwarden.com/signup), search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
