### ISSUE TITLE
Improve Main Vault view for multiple organisations by filtering

### ISSUE THREAD

**Issue by theWeird** [bitwarden/web#461]
I just imported password lists from passman to bitwarden for myself, my family, a small startup and the company I am working for.

So now I ended up with my personal passwords and 3 organizations all with their own passwords and collections.

In the main view of the vault, it is now hard for me to keep an overview of my private passwords and folders, because of the huge mix with organizational passwords. I'd prefer to have an option to hide all or specific organizations from the main view since they are available from the organization list, too.

Maybe there could be some kind of Tab-Navigation to switch between private and organization passwords, that not only filters the password list but also collections and folders containing no elements for the current selection.

In my opinion this would make it way more easy to keep track of private and organizational passwords.

**Comment by kspearrin** [comment]
We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one.

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
