### ISSUE TITLE
Keepass Import creates duplicate collections

### ISSUE THREAD

**Issue by derlucas** [bitwarden/web#491]
When importing a KeepassX CSV file using the import function it will generate duplicate collections with the same name for each import process.

Then there is no way in the manage collection Web GUI to determine the correct Collection to remove after moving all entries from the duplicate to my original collection.

**Comment by kspearrin** [comment]
It is expected to complete the entire import process in one prodecure. Duplicate import attempts with result in duplicate data.

**Comment by jcouturier** [comment]
I'm seeing the same issue, but it has nothing to do with multiple import attempts. The KeePassX file includes history for each item, and BitWarden is important each line of that history as a duplicate item rather than just the most recent version of the item.
For example: if I have username/password saved in KeePassX for Example.com, and in KeePassX I have updated that password 3 times over the last year, KeePassX retains that history. Then, when I Import the KeePassX data into Bitwarden, instead of Bitwarden displaying the most recent entry for Example.com, it displays 3 entries all with the same modified date (the import date). So it's nearly impossible to tell which is the current entry.
