### ISSUE TITLE
Tune the weak passwords report threshold

### ISSUE THREAD

**Issue by Mart124** [bitwarden/web#495]
Hi,

Due to #445, score 3 passwords do not show up anymore in the weak passwords list.

I would be pleased to see them back in the list.
Perhaps we could then use the new organization password strength policy score as the threshold for weak passwords report ?
We would then be able to "tune" it, passwords below the organization policy would show-up, which rather makes sense.

Thank you 👍

**Comment by kspearrin** [comment]
We use GitHub issues as a place to track bugs and other development-related issues. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one.

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!

**Comment by Mart124** [comment]
@kspearrin I think this is more a regression report than a feature request ? :confused:
Could we then reopen this please ?
Thank you again 👍

**Comment by kspearrin** [comment]
This isn't a regression. This was a decided change. If you want to make this report configurable via policy, as suggested, that would be a new feature request.

**Comment by Mart124** [comment]
This was just an idea on how to achieve this.

We could also think about a simple dropdown in the weak passwords report, so that user can choose between passwords below "strong" threshold, or passwords below "good" threshold.
With a "strong" value by default then.

We can't ask users to check / correct their "good" passwords (to make them "strong") anymore, because they do not show-up in the report anymore, this is why I see this as a regression 😕
