### ISSUE TITLE
Password generation rules are not fully obeyed

### ISSUE THREAD

**Issue by sov-j** [bitwarden/web#497]
Password generator seems to not fully obey password generation rules selected.

**Environment:** 
Google Chrome  version 80.0.3987.132 (Official Build) (64-bit) 
Bitwarden version 2.13.1, vault.bitwarden.com

**Bug reproduction steps:**

1. Log in as a user
1. Select „Tools” in main menu
1. Set radio button to „Password”
1. Set check boxes „A-Z”, „a-z”, „0-9” and „Avoid Ambiguous Characters ”
1. Enter 5 into “Length” field (or anything – must be the same as #2 below)
1. Enter 5 into “Minimum Numbers” field
1. Enter 0 into “Minimum Special” field
1. Click “Regenerate password” button 

**Actual results:**
We have password which has length = 7 instead of 5. It contains 5 numbers, 1 capital letter and 1 small letter.

**Expected results:**
We have password which has length = 5 and contains only 5 numbers. 

See example on the screenshot below:
![image](https://user-images.githubusercontent.com/61802932/76699189-40279c80-66ab-11ea-9f5d-37c267fee399.png)

**Comment by vincentsalucci** [comment]
@sov-j Thanks for the bug report.

I wanted to provide a little more context into the problem and solution. 

Problem: During password generation, all applied options are taken into account.  In your example, Uppercase, Lowercase, and Numbers were required. Because the length and minimum numbers were the same value, the generator had to also add an uppercase letter and a lowercase letter in order to meet the requirements you've set. This results in the password length being 7 characters (5 numbers, 1 lowercase, and 1 uppercase).

Solution: We've updated the code to reflect any length changes made behind the scenes by the generator during generation.

**Comment by sov-j** [comment]
Checked on 2.13.2, it is indeed fixed. Thank you!
