### ISSUE TITLE
After removing cookies and other site data, the user is still able to use their Vault

### ISSUE THREAD

**Issue by sov-j** [bitwarden/web#504]
This looks like a single root cause to me, but there are two slightly different scenarios, both of them reported here. Feel free to let me know if you think I should split them.

**Environment:**
Google Chrome  version 80.0.3987.132 (Official Build) (64-bit) 
Bitwarden version 2.13.1, vault.bitwarden.com

**Bug reproduction steps:**
1. Log in as a user
2. Check that My Vault page (https://vault.bitwarden.com/#/vault) is opened
3. Clear browser history (In Chrome: History→Clear Browing Data → Basic: History, Cookies and other site data, Cached images and files)

![image](https://user-images.githubusercontent.com/61802932/77299480-cb78e180-6cec-11ea-8568-64a04598aed4.png)

4. Get back to My Vault tab
5. *[this illustrates the first scenario]* Click any Vault entry

**Actual result:** Vault Edit Item page opens, but it lacks any fields, just header and footer

**Expected result:** Bitwarden asks the user to login

![image](https://user-images.githubusercontent.com/61802932/77299592-fd8a4380-6cec-11ea-993f-96dc576e04e5.png)

6. Click Cancel on the Vault Edit Item form
7. *[this illustrates the second scenario]* Click any item in the main manu, for example Tools
8. Click on My Vault to get back to the Vault page
9. Click any Vault entry

**Actual result:** Vault Edit Item page opens, with all the item data available

**Expected result:** Bitwarden asks the user to login

![image](https://user-images.githubusercontent.com/61802932/77299669-1bf03f00-6ced-11ea-8de8-f68aaac711df.png)

**Comment by ajayyy** [comment]
The data is stored in RAM for that session.

**Comment by sov-j** [comment]
Checked on 2.13.2 (I see the version was updated), it is still reproducible.

**Comment by ajayyy** [comment]
This is intended behaviour and there is no way to fix it. The data is not stored in RAM, not in any browser storage. Reloading the page or restarting the browser will clear that data.

**Comment by setyb** [comment]
@sov-j This appears to at least be an issue regarding poor UX in Google Chrome, and it may be worth reporting this UX issue in the chromium repo.

When the user selects "Cached images and files" in Google Chrome they likely want to delete everything in the RAM cache too.  Technically speaking, it's likely not implemented as a typical cache, but there is no way for the average user to know this.  Heck, many people don't even know how to pronounce "cache".

It's worth noting that Firefox has an option to clear "Active Logins" in addition to just clearing cookies.  You may want to look at switching to Firefox.

After clearing cookies, if Google Chrome (or any browser) allows you to make more network requests to an HTTPS host (such as vault.bitwarden.com) without logging back in, that's a serious bug with the browser.  I'm only somewhat familiar with all the code in this repo, but someone else (perhaps @ajayyy ) should be able to confirm whether or not a network request needs to be made to perform steps 8 or 9 in your issue report.  If you're familiar with Chrome's devtools, you can also look at the network logs there (or use any network inspector).

I just tried clearing all cookies in Firefox, and clicked on another GitHub page in my account.  As expected, because loading that page required a network request, GitHub insisted on credentials before proceeding.

I'm pretty sure (but not 100%) that as long as network requests are not performed, cookies are not checked by any commonly used web browsers.  Hopefully someone else can confirm or correct me.

That said, it is likely possible to write some special code to detect when the user has cleared the browser's cookies or cache (for cache, it likely would not be able to detect the difference between the user clearing the cache versus items being pushed out of the cache by newer items).  It will need to be determined whether or not supporting one or both of those cases is worth the time invested to develop and test the code.

**Comment by ajayyy** [comment]
That is a good point. The authentication is probably failing, while the data already cached in the client is working fine. That would explain the blank windows.
