### ISSUE TITLE
Feature Request : Virtual Keyboard for password input in login page

### ISSUE THREAD

**Issue by Chidhambararajan** [bitwarden/web#529]
I am really happy with the way bitwarden works. 

I know that the web console is available so that you can access your random generated passwords from bitwarden in the devices that you don't own or haven't setup bitwarden

I think it will be better if offered a virtual keyboard input for password in login area to prevent the user from KeyStroke sniffing attacks in public systems.

Bitwarden is so awesome.. it will be even better with this feature : )

**Comment by kspearrin** [comment]
We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one.

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
