### ISSUE TITLE
U2F doesn't seem to work on iOS

### ISSUE THREAD

**Issue by rggjan** [bitwarden/web#560]
I can't select the U2F 2FA method on iOS in Safari, even though it should be supported (https://www.yubico.com/blog/native-support-for-webauthn-and-fido-is-finally-here-on-iphones-and-ipads/). It works fine on OSX in Safari.

**Comment by bcronce** [comment]
Support is currently estimated for next year according to their roadmap https://community.bitwarden.com/t/bitwarden-roadmap/12865

On my android, I also registered my yubikey as a yubikey device instead of U2F/fido. While it is an OTP, which can technically be phished, for me it was just as smooth as U2F, held against my phone and logged in. I say technically because I believe yubikey OTP requires communicating back to yubikey servers, and the service is not free. I would find it strange for an attacker to register and pay for such a service and attempt to phish another site.

**Comment by cscharf** [comment]
This support is planned when we roll the U2F/fido functionality currently on our roadmap. Until then closing this issue.
