### ISSUE TITLE
Renaming a parent folder does not rename the child folders

### ISSUE THREAD

**Issue by cg3** [bitwarden/web#587]
## Describe the Bug

Renaming a parent folder with child folders in it will only rename the top folder.
All child folders will have the old name.

worx
-child1
-child2

rename folder worx to work
work
worx/child1
worx/child2

Instead all child folder should get the new name.

## Steps To Reproduce

1. Create a folder structure with sub folders in it.
2. Rename the parent folder.
3. All child folders are vivible with old name, renamed parent folder is empty.

## Expected Result

All child folders are under the new name and get renamed accordingly.

## Actual Result

All child folders are left untouched and only the parent folder is renamed.

**Comment by sov-j** [comment]
Hi, @cg3, 

I understand what you mean, but Bitwarden does not have "real" nested folders. By renaming parent folder you create a situation described in Bitwarden's help on folders: 

> If a folder’s name contains the forward slash delimiter, yet no “parent” folder exists, its name will be displayed in its entirety. In the example shown above, a folder named “Finance/Banking” would not produce a nested structure. You would need to create a “Finance” folder as well if nesting is desired.

See last paragraph here: https://bitwarden.com/help/article/folders/

**Comment by cscharf** [comment]
Thank you for reporting this, it's much appreciated. We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one.

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
