### ISSUE TITLE
Back button broken on https://vault.bitwarden.com

### ISSUE THREAD

**Issue by lgommans** [bitwarden/web#6]
1. Open https://vault.bitwarden.com
2. Try to go back

Expected result: you return to the previous page

Actual result: you remain on the current page

System details: Debian Stretch (testing); Firefox 49.

**Comment by kspearrin** [comment]
This one is a bit weird.

It happens because of this line: https://github.com/bitwarden/web/blob/master/src/Web/wwwroot/app/config.js#L132

Basically, if you are not logged in and try to access `/` you get redirected to to `/login`. if you hit back on login it tries to take to you to the previous page, which was `/`, then the loop kicks back in again never letting you go back.

Not sure how to fix this at the moment.

**Comment by kspearrin** [comment]
Resolved with next version.
