### ISSUE TITLE
Security key authentication loops infinitely when failed

### ISSUE THREAD

**Issue by Zer0t3ch** [bitwarden/web#602]
## Describe the Bug
When attempting to log in, the 2FA page will infinitely loop security key "requests" (sorry I don't know the correct term) if anything other than a correct key is found

## Steps To Reproduce
Insert a security key not configured for BitWarden and attempt to log in

## Expected Result
Should prompt 1-3 times for U2F keys before erroring and waiting for user input in the DOM to request further security key attempts

## Actual Result
Infinite loop of requests

## Environment

- Operating system: Windows 10
- Browser: MS Edge (Chromium) 84.0.522.59
- Build Version (Bottom of the page): 2.15.1

**Comment by clayadams5226** [comment]
This is currently the expected functionality. 

The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one.

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
