### ISSUE TITLE
store and display last login usage

### ISSUE THREAD

**Issue by nilsbecker** [bitwarden/web#61]
it would be helpful to be able to find out when each login in the web vault was last used/accessed. 

this can help tremendously when trying to identify which one out of a number of equally-named logins is the valid one, and when weeding out old stale logins.

**Comment by kspearrin** [comment]
We are moving away from tracking Bitwarden feature requests like this one as GitHub issues. We have created a [Bitwarden Community Forum](https://community.bitwarden.com) which has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests).

Please [sign up on our forums](https://community.bitwarden.com/signup), search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
