### ISSUE TITLE
Items don't appear in vault when assigned to multiple groups

### ISSUE THREAD

**Issue by clayadams5226** [bitwarden/web#629]
## Steps To Reproduce

Log into an Agency with over 500 passwords and 200 collections
Create a user with a manager role
Create 2 user groups splitting the collections evenly among the groups
Assign the above manager to both user groups
Log in as the above user

## Expected Result

User is able to see all the collections and passwords

## Actual Result

User is able to see all the collections but they are void of any items
## Environment

- Operating system: [e.g. Windows 10, Mac OS Catalina]
- Browser: [e.g. Firefox 73.0.1]
- Build Version (Bottom of the page): [2.13.0]

**Comment by vincentsalucci** [comment]
@cscharf @kspearrin - After a couple days of testing, I believe I've pinpointed the cause.

### Contributing factors
 - After building a local db to the requirements of this task, the issue could not be replicated.
 - In order to successfully replicate, all organizational information from a production org was imported.
   - There are over 8,000 ciphers
   - There are over 300 collections

### Root cause
> Saving the JSON'ified Cipher into the `sessionStorage` using the `setItem` function.

### Information retrieved from `sessionStorage.setItem(..)`
<img width="700" alt="Screen Shot 2020-09-04 at 3 47 16 PM" src="https://user-images.githubusercontent.com/26154748/92284207-34cd6500-eec7-11ea-9f4c-421158b606cf.png">

### Testing to verify
 - Used `Firefox` as the browser 
 - Tested `sessionStorage` capacity using [this](http://dev-test.nemikor.com/web-storage/support-test/)
    - Result: 
<img width="915" alt="Screen Shot 2020-09-04 at 4 11 23 PM" src="https://user-images.githubusercontent.com/26154748/92285266-7bbc5a00-eec9-11ea-9878-108e0b6eb146.png">

 - The following was adjusted in the `htmlStorage.service.ts` for the `web` vault.

```
save(key: string, obj: any): Promise<any> {
        if (obj == null) {
            return this.remove(key);
        }

        const json = JSON.stringify(obj);
        if (this.isLocalStorage(key)) {
            window.localStorage.setItem(key, json);
        } else {
            if (key.includes('ciphers_')) {
                // tslint:disable-next-line
                console.log('ZZZ: Youve enter the ciphers try block');
                try {
                    window.localStorage.setItem(key, json);
                } catch (e) {
                    // tslint:disable-next-line
                    console.log('ZZZ: ' + e);
                }
            } else {
                window.localStorage.setItem(key, json);
            }
        }
        return Promise.resolve();
    }

```
#### Output
`ZZZ: QuotaExceededError: The quota has been exceeded.`

 - This error matches those within the accepted response [here](https://stackoverflow.com/questions/3027142/calculating-usage-of-localstorage-space)
 - The causes no `ciphers` to be found within the `sessionStorage`, yielding the same empty listing found in the bug description above.

#### Resolution
 - How should we approach adjusting the saving of ciphers inside the `sessionStorage`?
