### ISSUE TITLE
Security: CSP provided on vault.bitwarden.com is far too permissive, grants three third parties potential access to passwords

### ISSUE THREAD

**Issue by sneak** [bitwarden/web#659]
## Describe the Bug

Many third party organizations are able to execute javascript in the context of the Vault web application.

The following is the CSP header from the server for `vault.bitwarden.com`:
```
content-security-policy: default-src 'self'; script-src 'self' 'sha256-ryoU+5+IUZTuUyTElqkrQGBJXr1brEv6r2CA62WUw8w=' https://js.stripe.com https://js.braintreegateway.com https://www.paypalobjects.com; style-src 'self' 'unsafe-    inline' https://assets.braintreegateway.com https://*.paypal.com; img-src 'self' data: https://icons.bitwarden.net https://*.paypal.com https://www.paypalobjects.com https://q.stripe.com https://haveibeenpwned.com https://www.g    ravatar.com; child-src 'self' https://js.stripe.com https://assets.braintreegateway.com https://*.paypal.com https://*.duosecurity.com; frame-src 'self' https://js.stripe.com https://assets.braintreegateway.com https://*.paypal    .com https://*.duosecurity.com; connect-src 'self' wss://notifications.bitwarden.com https://notifications.bitwarden.com https://cdn.bitwarden.net https://api.pwnedpasswords.com https://twofactorauth.org https://api.stripe.com     https://www.paypal.com https://api.braintreegateway.com https://client-analytics.braintreegateway.com https://*.braintree-api.com; object-src 'self' blob:;
```

## Steps To Reproduce

Visit `vault.bitwarden.com` in a browser.

## Expected Result

Only Bitwarden code executes.

## Actual Result

Stripe, Braintree, and PayPal javascript can execute in the context of the SPA, optionally stealing my master passphrase and/or all of my stored passwords.  The security of my passwords depends entirely on the trustworthiness of Stripe, Braintree, or PayPal (at their sole option) not ever being compromised or otherwise coerced to backdoor the Vault web application to steal passwords.

**Comment by sneak** [comment]
The fix for this, I believe, is to host all of the Bitwarden subscription payment processing on a different second-level domain.

(Or host the vault app on a different second-level domain.)

**Comment by mortensales** [comment]
What about users who only use the free bitwarden plan? Can they too have their information accessed by e.g. PayPal?

**Comment by cscharf** [comment]
@mortensales , re:
> What about users who only use the free bitwarden plan? Can they too have their information accessed by e.g. PayPal?

No, only when you go to sign up for premium, and then only when you select a provider, does the application dynamically load the appropriate payment provider scripts or iframe. We do not simply willy-nilly include those scripts on every page of the vault.

@sneak , re:
> The fix for this, I believe, is to host all of the Bitwarden subscription payment processing on a different second-level domain, and to factor out the payment portions of this app into a dedicated payments app that can be so hosted.

We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one.

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!

**Comment by sneak** [comment]
> We use GitHub issues as a place to track bugs and other development related issues. The Bitwarden Community Forums has a section for submitting, voting for, and discussing product feature requests like this one.

Like the others, this is a vulnerability report, not a feature request.  Due to your refusal to fix the other security issues reported, I've got to spend time migrating a few dozen seats off of the product this week.  I won't be requesting any feature improvements any time soon.

**Comment by srd424** [comment]
Any chance we can get some input from @kspearrin? I realize security is a never-ending activity and priorities need to be set, but I feel this issue's been dismissed a little quickly..
