### ISSUE TITLE
Reused Password Report does not respect Domain Rules

### ISSUE THREAD

**Issue by Iotaslair** [bitwarden/web#674]
## Describe the Bug

I recently went to check my Reused password report and I noticed that some websites that have different URLs but are for the same company (mojang.com and minecraft.net) have been reported as having a repeated password even though they have a domain rule to say they are supposed to share the same password.

## Steps To Reproduce

1. Have two accounts with the same password for different websites. I used mojang.com and minecraft.net
2. Go to Settings
3. Go to Domain Rules
4. Set the two domains to be equal to one another. 
5. Go to Tools
6. Go to Reused Password Report
7. Note that the two accounts still appear on the report even though they are set to be the same

## Expected Result

I expect the two websites to not show up on the report since I set them to be treated as equal in the software

## Actual Result

They show up in the report

## Screenshots or Videos

N/A

## Environment

- Operating system: Windows 10
- Browser: Chrome 
- Build Version (Bottom of the page): 86.0.4240.75

**Comment by clayadams5226** [comment]
We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one.

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
