### ISSUE TITLE
Provide a way to inspect duplicate passwords

### ISSUE THREAD

**Issue by dralley** [bitwarden/web#69]
Many people re-use passwords between websites, even though it's bad practice.  Should a user want to rectify that, it would be nice to have a convenient way to see for which sites they are using similar or identical passwords.  

A suggestion would be to group the websites into dropdown lists below each password, where the password is obscured by dots but revealable by clicking one of the little eye icons.  Later on, it would be easy to expand this view to include other forms of password strength checking if that's something that is on the roadmap.

**Comment by kspearrin** [comment]
There are plans to bring "password higene" reports and this is a pretty good idea to fit into that scope.

**Comment by brianredbeard** [comment]
Medium (currently going offline in 3 weeks) provides something of the following form (usernames masked with `gedit`):
![screenshot from 2017-06-13 19-16-52](https://user-images.githubusercontent.com/57542/27112779-f761cecc-506d-11e7-9672-a04057f0296b.png)

**Comment by dralley** [comment]
That looks really good!  The only thing I would suggest is that there should some way to view which other sites are using the same password instead of just a generic "re-used 3 times"

**Comment by dasm** [comment]
@kspearrin any progress with this?
And, if we're onto this, would it be possible to implement/add feature to remind about changing a password?
I'm guilty of not doing this regularly. Once created, password can leave even years. Would it be nice to have some kind of way, of saying: "This password wasn't changed in last 3 months. Consider update" or similar.

**Comment by nopynoop** [comment]
Any updates on the password higene features?

**Comment by kspearrin** [comment]
We are moving away from tracking Bitwarden feature requests like this one as GitHub issues. We have created a [Bitwarden Community Forum](https://community.bitwarden.com) which has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests). Please [sign up on our forums](https://community.bitwarden.com/signup) if you want to continue contributing to feature requests.

Since this was a popular feature request we have already re-created it on the forums and linked back to this GitHub issue for reference. You can vote for this feature request there if you'd like.

https://community.bitwarden.com/t/password-checkup-locate-old-reused-and-insecure-passwords/206

This issue will now be closed. Thanks!
