### ISSUE TITLE
Reports do not show accurate information when the page is refreshed.

### ISSUE THREAD

**Issue by SergeantConfused** [bitwarden/web#693]
## Describe the Bug
When viewing the reports below, hitting Refresh (F5) and unlocking the vault shows a page displaying a green banner that everything is OK.

Exposed Passwords Report
Reused Passwords Report
Weak Passwords Report
Inactive 2FA Report

## Steps To Reproduce
1. Add a login item with a common password and assign it to a URI that supports 2FA. I used outlook.com.
2. Go to Tools > Inactive 2FA Report. You will see this item marked as a login with no 2FA.
3. Click on Refresh (F5).
4. Unlock your vault.

## Expected Result
To see the item marked as lacking 2FA.
## Actual Result
We see that everything is OK.

## Screenshots or Videos
![1](https://user-images.githubusercontent.com/73389600/98536982-83f59480-2280-11eb-9096-83c0167c8560.png)
![2](https://user-images.githubusercontent.com/73389600/98536984-848e2b00-2280-11eb-979e-736655a39d51.png)

## Environment

- Operating system: Windows 10 Pro.
- Browser: Chrome Version 86.0.4240.183.
- Build Version (Bottom of the page): Version 2.16.2.

## Additional Context
N/A.

**Comment by gzachos** [comment]
Thanks @SergeantConfused for creating this ticket.

This issue was initially encountered in the following environment:

- Operating system: Linux Mint 20
- Browser: Mozilla Firefox `82.0.2` (64-bit)
- Bitwarden Web Vault: `Version 2.16.2`

and was reproduced on the same system using browser:  Chromium `Version 86.0.4240.183` (Official Build) for Linux Mint (64-bit)

**Comment by kparaju** [comment]
I believe this happens because the passwords have not been decrypted yet. if you go back to "My vault" and come back to the page it works. 

Before refresh:
![before_refresh](https://user-images.githubusercontent.com/334184/108927677-be582700-760e-11eb-827d-2dbb71b53612.PNG)

After refresh:
![after refresh](https://user-images.githubusercontent.com/334184/108927695-c57f3500-760e-11eb-989a-27dbddb3f296.PNG)

After refresh and them going to "My vault" and waiting for it to load:
![after_refresh_visit_my_vault](https://user-images.githubusercontent.com/334184/108927722-d039ca00-760e-11eb-9439-51403b6908dd.PNG)

I'll clone the repo and poke around. I believe the issue is that going to "My vault" actually is when Bitwarden does the decryption. Going directly to tools will make that UI think that you don't have any saved passwords so we get the "GOOD NEWS" message.
