### ISSUE TITLE
Colon breaks field search

### ISSUE THREAD

**Issue by AdamVB** [bitwarden/web#698]
## Describe the Bug

When putting a colon ":" in the vault search it does not search all fields of a vault entry, just the name/title. URI Field somehow is not parsed properly/completely

## Steps To Reproduce

Create Two Vault Entries like this:

Entry 1:
```
  Name: Test1 https://192.168.1.1:623
  Username: test1
  Uri1: https://192.168.1.1:623
```
Entry2:
```
  Name: Test2
  Username: test2
  Uri1: https://192.168.1.1:623
```

Then search the searchbar for ```https://192.168.1.1:623``` and also ```192.168.1.1```

## Expected Result

I would expect the search result to show both entries when using both search terms.

## Actual Result

When searching for ```https://192.168.1.1:623``` it only shows Entry1, but not Entry2.

When searching for ```192.168.1.1:``` it only shows Entry1

When searching for ```192.168.1.1``` it shows both entries.

## Screenshots or Videos

![grafik](https://user-images.githubusercontent.com/15871966/98795203-3f960000-240a-11eb-95c0-82b82884a969.png)

![grafik](https://user-images.githubusercontent.com/15871966/98795168-360c9800-240a-11eb-8cfc-bbcd33a12057.png)

![Screenshot 2020-11-11 103130](https://user-images.githubusercontent.com/15871966/98794979-f8a80a80-2409-11eb-95f0-55dd5f2f4e55.png)
![Screenshot 2020-11-11 103037](https://user-images.githubusercontent.com/15871966/98794964-f3e35680-2409-11eb-95f6-58fb3f631c9a.png)
![Screenshot 2020-11-11 103111](https://user-images.githubusercontent.com/15871966/98794976-f6de4700-2409-11eb-919a-afd84b4c79ca.png)

## Environment

- Operating system: Debian 10 (server) Windows 10 (client)
- Browser: Chrome 84.0.4147.89
- Build Version (Bottom of the page): 2.16.1

## Additional Context

Adding ```https://192.168.1.1:623``` in the Notes field or any other custom field does not change the outcome as they are probably searched/parsed the same way as the uri field.

**Comment by clayadams5226** [comment]
Hi @AdamVB  This is the current expected behavior. Adding a colon enables advanced searching for a specific field. See:
https://lunrjs.com/guides/searching.html#fields
https://bitwarden.com/help/article/searching-vault/#advanced-search-examples

To open a feature request please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
