### ISSUE TITLE
Allow U2F in Microsoft Edge

### ISSUE THREAD

**Issue by timcappalli** [bitwarden/web#703]
## Describe the Bug

U2F is not presented as a second factor option in Microsoft Edge. It is fully supported in Microsoft Edge. I'm guessing some UA detection is happening and Edge was not added

## Steps To Reproduce

Navigate to vault.bitwarden.com in Microsoft Edge (current version is 86).
Login with username and password
On the "Authenticator App" screen select "Use another two-step login method"

## Expected Result
Security key should be default like on other platforms and should be present in the two step login method list

## Actual Result

TOTP is the default and security key is not available in the two-step login method

## Screenshots or Videos

![image](https://user-images.githubusercontent.com/6476604/99012281-ff26a700-251b-11eb-818f-ad9268817e21.png)

## Environment

- Operating system: `macOS 11`
- Browser: `Edge 87.0.664.30`
- Build Version (Bottom of the page): `2.16.2`

**Comment by clayadams5226** [comment]
This feature is currently on our roadmap for later this year. 
https://community.bitwarden.com/t/u2f-support-for-additional-bitwarden-clients/11867/14

**Comment by kspearrin** [comment]
@clayadams5226 I think this is different than the linked feature request. This is for U2F support in the web vault, which we already support. The problem is that we assume Edge does not support U2F, which was the case in the past, but the new Edge version does support it. We just need to whitelist Edge for U2F support now.
