### ISSUE TITLE
Shared passwords from a deleted organisation

### ISSUE THREAD

**Issue by iain-id** [bitwarden/web#71]
I started testing BitWarden with a free account and then deleted the organisation when I was ready to do a full test and created a new organistaion with a team licence.  After I deleted the organization the passwords I had shared now show up as [Error: cannot decrypt].  I am able to delete the shared logins but not the collections.

![image](https://cloud.githubusercontent.com/assets/28516860/26657109/3bdce242-46b6-11e7-9db5-c4f229796c93.png)

Regards

Iain

**Comment by kspearrin** [comment]
Weird. Was there any indication of an error when you deleted the organization? Can you send an email to https://bitwarden.com/contact so I can get your email address to lookup the status of the organization and see what happened?

**Comment by iain-id** [comment]
Thanks, I have sent you an e-mail.  There was no error that I am aware of when I deleted the organisation.

**Comment by kspearrin** [comment]
The issue here appears that the organization failed to delete, however, the local org encryption key was removed from your login session still. After logging out and back in @iain-id was able to decrypt things again properly and delete the organization.

I am not sure why it failed the first time deleting, so I will leave this issue open for more investigation.

**Comment by kspearrin** [comment]
This has now been resolved for the next version to be released with https://github.com/bitwarden/core/commit/151eae2f05e1ff13f799fbc2c84e763266cd7349

Thanks for the report!
