### ISSUE TITLE
Receiving An unexpected error has occured when trying to log into the web vault on Legacy Edge. 

### ISSUE THREAD

**Issue by SergeantConfused** [bitwarden/web#732]
## Describe the Bug
When trying to log into the web vault on Legacy Edge, you receive a red error banner stating 'An unexpected error has occurred' when you click on Log in.

## Steps To Reproduce
1. Go to the web vault.
2. Enter your credentials.
3. Click on Log In.

## Expected Result
To log into the web vault.

## Actual Result
Receive a red error banner stating 'An unexpected error has occurred'.

## Screenshots or Videos
![image](https://user-images.githubusercontent.com/73389600/101524655-1e312100-3982-11eb-8996-a755943f5648.png)

## Environment

- Operating system: Windows 10 2004.
- Browser: Legacy Edge 44.19041.
- Build Version: 2.17.0.

## Additional Context
This was also reproduced on Legacy Edge 44.1776 running on Windows 10 1809.

**Comment by vachan-maker** [comment]
Use the new Edge (based on chromium) 
https://www.microsoft.com/en-us/edge
In the future, most websites may not support legacy edge.

**Comment by clayadams5226** [comment]
Thank you for getting in touch and bringing this to our attention! We'd like to assist you further. We ask that you please contact us using our contact page, here: https://bitwarden.com/contact. You can include a link to this issue in the message content. The issue here will be closed and moved over to our Help Desk.
