### ISSUE TITLE
Improvement of group management

### ISSUE THREAD

**Issue by brianredbeard** [bitwarden/web#75]
As an administrator it is easier to select a group in the interface and select the users for the group rather than making individual modifications on dozens (or more) users at a time.

**Comment by kspearrin** [comment]
I agree and can see where that could become a pain to manage with larger organizations. The same thing could be said for managing a collection as well.

**Comment by pauldalewilliams** [comment]
This would be an important improvement for enterprise use.  I'm investigating it now for a small team, and I found this would be painful if we made it available to more of our staff.  (Painful for me at least.)

**Comment by kspearrin** [comment]
We are moving away from tracking Bitwarden feature requests like this one as GitHub issues. We have created a [Bitwarden Community Forum](https://community.bitwarden.com) which has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests). Please [sign up on our forums](https://community.bitwarden.com/signup) if you want to continue contributing to feature requests.

Since this was a popular feature request we have already re-created it on the forums and linked back to this GitHub issue for reference. You can vote for this feature request there if you'd like.

https://community.bitwarden.com/t/improve-group-management/234

This issue will now be closed. Thanks!
