### ISSUE TITLE
[Suggestion] Move favorites to the side panel

### ISSUE THREAD

**Issue by ClarkeCC** [bitwarden/web#76]
Having the favorites folder on the side panel would be great!

**Comment by kspearrin** [comment]
It would not fit.

**Comment by ClarkeCC** [comment]
@kspearrin how so? Would it not just act as a regular folder?

**Comment by kspearrin** [comment]
@ClarkeCC I think I misunderstood you originally. Yes it will work there.

**Comment by ClarkeCC** [comment]
Whoops closed the thread by accident.

**Comment by kspearrin** [comment]
We are moving away from tracking Bitwarden feature requests like this one as GitHub issues. We have created a [Bitwarden Community Forum](https://community.bitwarden.com) which has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests).

Please [sign up on our forums](https://community.bitwarden.com/signup), search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
