### ISSUE TITLE
Move multiple secrets between collections

### ISSUE THREAD

**Issue by nickjmv** [bitwarden/web#771]
I noticed I could not select multiple secrets (already inside a collection) and move them all together to another collection.

Is this something to be implemented?

**Comment by SergeantConfused** [comment]
Hi there,

Please consider joining our community and voting for this feature request here: https://community.bitwarden.com/t/bulk-collection-migration/14489.


All the best,

**Comment by clayadams5226** [comment]
We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one.

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
