### ISSUE TITLE
[self-hosted] getting the correct url in the verification e-mail

### ISSUE THREAD

**Issue by gunslingerfry** [bitwarden/web#777]
## Describe the Bug
I have an apache proxy frontend handling the ssl certificate and bitwarden as subdomain bw.xxx.xxx

So I believe it's going:
bitwarden docker nginx <=> localhost:8000 <=> proxy/reverse proxy bw.xxx.xxx

I set up the verification/admin e-mail account properly and they are received but the button is using the nginx address, not the subdomain. Like so:
http://localhost/admin/login/confirm?returnUrl=&email=...

I can't set the global override env file base urls otherwise it breaks my proxying. Is there a way to just set the external domain name for the purposes of verification e-mails?

## Expected Result
A way to override the url given in the verification e-mail to match the external url

## Actual Result
The verification e-mails use the base urls in the global override conf

## Environment

- OS: Ubuntu 20.04
- Webserver: Apache 2.4.46
- Build Version : [2.17.1]

**Comment by clayadams5226** [comment]
Hey @gunslingerfry are you still having this issue? 

We'd like to assist you further. We ask that you please contact us using our contact page, here: https://bitwarden.com/contact. You can include a link to this issue in the message content. The issue here will be closed and moved over to our Help Desk.
