### ISSUE TITLE
darkmode support

### ISSUE THREAD

**Issue by crowlKats** [bitwarden/web#778]
Are there any plans to have a darkmode?

**Comment by clayadams5226** [comment]
Hey @crowlKats, this has been discussed and is something that is currently on our backlog. 

We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one.
https://community.bitwarden.com/t/dark-mode-for-web-vault/6790

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
