### ISSUE TITLE
Use before-submission validation on Registration page

### ISSUE THREAD

**Issue by pkarjala** [bitwarden/web#8]
There is little immediate validation done on the registration page beyond the email address before pressing the submit button.  It is a best practice to do immediate validation and provide feedback for things such as:
- Email address
- Matching passwords
- Length / strength of passwords

**Comment by kspearrin** [comment]
Currently I reply on the HTML5 validation attributes to provide inline validation feedback. All other is handled on the server. Email address is already handled by this. I am not sure of any HTML5 validators for the others.

**Comment by kspearrin** [comment]
We are moving away from tracking Bitwarden feature requests like this one as GitHub issues. We have created a [Bitwarden Community Forum](https://community.bitwarden.com) which has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests).

Please [sign up on our forums](https://community.bitwarden.com/signup), search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
