### ISSUE TITLE
[Suggestion] Bookmarklets

### ISSUE THREAD

**Issue by Vistaus** [bitwarden/web#82]
LastPass has bookmarklets which you can use to autofill login prompt in unsupported browsers (i.e. browsers for which there is no official extension). It would be great if Bitwarden had these bookmarklets as well as I also frequently use unsupported browsers :)

**Comment by kspearrin** [comment]
We are moving away from tracking Bitwarden feature requests like this one as GitHub issues. We have created a [Bitwarden Community Forum](https://community.bitwarden.com) which has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests).

Please [sign up on our forums](https://community.bitwarden.com/signup), search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!

**Comment by Wowfunhappy** [comment]
I have created a thread at https://community.bitwarden.com/t/bookmarklet/6190, because there didn't seem to be one! @Vistaus you should vote for it!

**Comment by temp10min** [comment]
> 
> 
> I have created a thread at https://community.bitwarden.com/t/bookmarklet/6190, because there didn't seem to be one! @Vistaus you should vote for it!

Oops! That page doesn’t exist or is private.
