### ISSUE TITLE
[Suggestion] Vault Action

### ISSUE THREAD

**Issue by schmerold** [bitwarden/web#83]
I use the vault as a list of favorites.

On some sites, I have multiple logins at Amazon, I have business & personal
At PNC bank - business & personal etc

So two things, when I click on a site in the vault it would be better if it launched the site, you could add a gear icon to accommodate edits to the site.

Also, it would be good if Bitwarden was smart enough to know that I clicked on Amazon - Home, so it should use the Amazon home credentials when I select Amazon Home from the vault.

**Comment by kspearrin** [comment]
We are moving away from tracking Bitwarden feature requests like this one as GitHub issues. We have created a [Bitwarden Community Forum](https://community.bitwarden.com) which has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests).

Please [sign up on our forums](https://community.bitwarden.com/signup), search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
