### ISSUE TITLE
Wrong timestamps when password gets updated

### ISSUE THREAD

**Issue by Germs2004** [bitwarden/web#832]
## Describe the Bug

Sometimes, after changing a password on an entry, the "Password Updated" timestamp does not match the "Updated" timestamp.  In my case, they differed by 1 second. I guess it could be because the DateTime.Now() function was run twice to update each of the fields rather than being run once and that same value used for both fields.

## Steps To Reproduce
1) Create a password entry and save it.
2) Open that entry, change the password, and save it.
3) Open that entry again and see if the timestamps match.  If they don't, you have reproduced the bug.  If they do match, go to step 2 and repeat as many times as necessary until you reproduce the bug.

## Expected Result

The 2 timestamps should match when the last change you've made to an entry includes a password change.

## Actual Result

The 2 timestamps can sometimes differ by 1 second.

## Screenshots or Videos

![image](https://user-images.githubusercontent.com/5519340/108228963-56d14180-710d-11eb-9fab-bb260eed5522.png)

## Environment

- Operating system: Windows 10
- Browser: Chrome 88.0.4324.150
- Build Version (Bottom of the page): 2.18.1

**Comment by rubycoder** [comment]
I think there's a way to resolve this issue which also provides more fine grained information on when a particular entry was updated.

Currently:

When the password is changed, the Updated and Password Updated fields are set to the current time.
When anything else is changed, only the Updated field is set to the current time.

We could change this to:

When the password is changed, only the Password Updated field is set to the current time.
When anything else is changed, only the Updated field is set to the current time.

Currently, when the password is changed, we lose the timestamp indicating when the other fields were last changed.  With this change we could see that the password was changed last week, but the other fields haven't been changed in two years.  I'd find this information very useful.

Since the Updated and Password Updated fields will never be set to the same value, this avoids the issue with two values that should be the same differing by one second.
