### ISSUE TITLE
[Suggestion] Copy TOTP from vault list and context menu

### ISSUE THREAD

**Issue by schmerold** [bitwarden/web#84]
When on a site with a TOTP code stored in Bitwarden, it would be helpful if the context menu & vault menu offered a "Copy TOTP" shortcut that would work like "Copy username" & "Copy password"

**Comment by kspearrin** [comment]
Problem here is with the existing design we're starting to run out of room.

**Comment by schmerold** [comment]
Agreed. BTW both my suggestions should have been posted to https://github.com/bitwarden/browser
It will be the same issue there as well.

**Comment by mcg** [comment]
"Copy TOTP" is needed but how about after filling the login credentials, the TOTP code could be copied to the clipboard for easy pasting in the inevitable next step in the process?

**Comment by kspearrin** [comment]
@mcg this is already done on all applications except Firefox, which does not allow access to the clipboard from the background.

**Comment by mcg** [comment]
Oh! That is fantastic... I'm using Firefox :-(

**Comment by kspearrin** [comment]
I found a workaround so this should be working in Firefox next release as well.

**Comment by kspearrin** [comment]
We are moving away from tracking Bitwarden feature requests like this one as GitHub issues. We have created a [Bitwarden Community Forum](https://community.bitwarden.com) which has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests). Please [sign up on our forums](https://community.bitwarden.com/signup) if you want to continue contributing to feature requests.

Since this was a popular feature request we have already re-created it on the forums and linked back to this GitHub issue for reference. You can vote for this feature request there if you'd like.

https://community.bitwarden.com/t/quick-copy-totp-code/38

This issue will now be closed. Thanks!
