### ISSUE TITLE
Make "Authenticator Key (TOTP)" as sensitive

### ISSUE THREAD

**Issue by avoidik** [bitwarden/web#842]
## Describe the Bug

I'd like to suggest to make "Authenticator Key (TOTP)" field of an item as sensitive/hidden by default, the same as for password.

## Steps To Reproduce

1. Go to any item in vault with enabled TOTP field
2. Click to open it
3. TOTP secret immediately disclosed

## Expected Result

Authenticator Key (TOTP) is hidden, and I can reveal it only when needed

## Actual Result

Authenticator Key (TOTP) is disclosed, can be accidentally leaked

## Screenshots or Videos

![image](https://user-images.githubusercontent.com/6435932/108685468-da6ba380-74fc-11eb-853f-90c9c668da57.png)

## Environment

- Operating system: Windows 10
- Browser: Firefox 85.0.2 (x64)
- Build Version (Bottom of the page): 2.18.1

**Comment by Greenderella** [comment]
Hi @avoidik 

We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one.

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!

**Comment by avoidik** [comment]
links for the reference

https://github.com/dani-garcia/bw_web_builds/issues/29

https://community.bitwarden.com/t/authenticator-key-totp-toggle-visibility-option/15068

**Comment by paulsteffen** [comment]
In my opinion there shouldn’t be a feature request necessary for this, it’s rather a security flaw to show the SECRET key each time when opening a data record.
