### ISSUE TITLE
Add secondary verification to Secure Notes

### ISSUE THREAD

**Issue by therealknight** [bitwarden/web#856]
This is mainly a feature I saw in LastPass and was something I used on a regular basis.

The ability to be able to have to secondary authenticate myself using my Master Password or a secondary password of some kind before accessing/modifying any secure notes.

**Comment by clayadams5226** [comment]
We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one.

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
