### ISSUE TITLE
Missing log out message when logging out from business portal

### ISSUE THREAD

**Issue by fgierlinger** [bitwarden/web#897]
## Describe the Bug

When logging out directly from the business portal, no proper log out message is displayed. Instead the placeholder text seems to be displayed.

![image](https://user-images.githubusercontent.com/2966031/112468201-447ba080-8d68-11eb-8c04-e1e53bc74531.png)

## Steps To Reproduce

1. Log in to Bitwarden 
2. Go to organisation policies (https://bitwarden.example.com/#/organizations/OrgID/manage/policies)
3. Open Business Portal (https://bitwarden.example.com/)
4. Log Out (user icon top right > Log Out)

## Expected Result
A proper log-out-message is displayed after pressing the log out button.

## Actual Result
The message "LoggedOutMessage" is shown.

## Environment

- Operating system: Windows 10
- Browser: Edge Version 89.0.774.57 (Official Build) (64-Bit)
- Build Version (Bottom of the page): [2.19.0]

## Additional Context
Error observed on self hosted deployment.

**Comment by kanish671** [comment]
I tried to figure out the issue here, and what I could conclude is that this issue is not fixable in this repository.
I think it is a matter of adding a message [here](https://github.com/bitwarden/server/blob/master/src/Core/Resources/SharedResources.en.resx) as the message is being rendered by [this](https://github.com/bitwarden/server/blob/master/bitwarden_license/src/Portal/Views/Auth/LoggedOut.cshtml) file
Adding an entry like below  in the `SharedResources.en.resx` should be fixing the issue, I believe.
```
<data name="LoggedOutMessage">
    <value>You have been logged out of this application.</value>
  </data>
```

**Comment by eliykat** [comment]
Hey @kanish671, you're 100% correct. Please submit a PR to the server repo if you'd like to contribute.

**Comment by kanish671** [comment]
Yes sure! I will create a PR.
Is the message `You have been logged out` fine?

**Comment by eliykat** [comment]
I assume it logs you out from the whole application (vault and business portal) - can you check this? If so, maybe just: `You have been logged out.`

**Comment by kanish671** [comment]
I am having a tough time trying to [setup the user secrets](https://github.com/bitwarden/server/blob/master/SETUP.md#setting-up-user-secrets). I have a macOS machine and I am running into version mismatch while following the docs. It asks me to install dotnet 2.2.0 while the website says that 2.2.0 has reached end of lifecycle. 

@fgierlinger could you please confirm the above for me? 
Or else I will go ahead and set it as `You have been logged out.` (A generic message makes more sense I guess)

**Comment by fgierlinger** [comment]
@kanish671  Negative, when selecting _Log Out_ in the business portal, you are only logged out from the business portal. The session in the vault is not affected from this action.

**Comment by kanish671** [comment]
Thank you! 
In that case, I think it would be best to inform the user that they have been logged out of the business portal.
`You have been logged out of the Bitwarden Business Portal` message makes sense the most. What do you think @eliykat ?

**Comment by eliykat** [comment]
OK good to know - thanks for checking @fgierlinger. @kanish671 please proceed with your suggested wording.

As an aside, `dotnet --version` for me returns `5.0.201`, so you definitely don't need to use `2.2.0`. If you need any help with the setup instructions, feel free to ask in our [dev chat](https://gitter.im/bitwarden/Lobby). And if it turns out to be a problem with our documentation, please create an issue or submit a PR so we can fix it up.

**Comment by kanish671** [comment]
@eliykat I have made the changes and created [this PR](https://github.com/bitwarden/server/pull/1249)

**Comment by cscharf** [comment]
Thanks @kanish671 , much appreciated. PR has been merged and will be included with the next server release.
