### ISSUE TITLE
[Feature Request] Trash Folder

### ISSUE THREAD

**Issue by omar-conti** [bitwarden/web#91]
Add section to store deleted items with possibility to restore them.

**Comment by rggjan** [comment]
Great idea, this is a must-have for accidentally deleted logins!

**Comment by kspearrin** [comment]
We are moving away from tracking Bitwarden feature requests like this one as GitHub issues. We have created a [Bitwarden Community Forum](https://community.bitwarden.com) which has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests). Please [sign up on our forums](https://community.bitwarden.com/signup) if you want to continue contributing to feature requests.

Since this was a popular feature request we have already re-created it on the forums and linked back to this GitHub issue for reference. You can vote for this feature request there if you'd like.

https://community.bitwarden.com/t/soft-delete-items-to-trash/32

This issue will now be closed. Thanks!
