### ISSUE TITLE
Include created_at and updated_at in export csv

### ISSUE THREAD

**Issue by dgleba** [bitwarden/web#92]
A request:

Can the  'created_at' timestamp  and  'updated_at'  timestamp  be included in the csv export?

Would those be the `CreationDate` and `RevisionDate` in the tables?

**Comment by kspearrin** [comment]
Would be pretty simple to do though I'm not really sure what value they add to a user exporting the data?

**Comment by dgleba** [comment]
It allows one to see what's changed recently and manage one's data using that information.

**Comment by kspearrin** [comment]
We are moving away from tracking Bitwarden feature requests like this one as GitHub issues. We have created a [Bitwarden Community Forum](https://community.bitwarden.com) which has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests).

Please [sign up on our forums](https://community.bitwarden.com/signup), search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
