### ISSUE TITLE
Search field suggestions

### ISSUE THREAD

**Issue by edouardmenayde** [bitwarden/web#93]
Hi there :-)
Just some suggestions regarding the search field :
    - The search field could be improved by having a little icon just to clear it quickly
    - The search field could be improved by clearing its content when clicking on vault (and maybe even the bitwarden icon) (I personally automatically think it's gonna send me back to my password list)

**Comment by kspearrin** [comment]
Point 2 is already the behavior.

**Comment by edouardmenayde** [comment]
I just tried it and it doesn't work but no error in the console when clicking. That's weird.

**Comment by jpbaril** [comment]
I would maybe move the search field to the right panel above the folder list. That would this way make every filtering features at the same place.

**Comment by kspearrin** [comment]
We are moving away from tracking Bitwarden feature requests like this one as GitHub issues. We have created a [Bitwarden Community Forum](https://community.bitwarden.com) which has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests).

Please [sign up on our forums](https://community.bitwarden.com/signup), search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
