### ISSUE TITLE
Bulk Actions > Share

### ISSUE THREAD

**Issue by tonygambone** [bitwarden/web#97]
It would be great to be able to select multiple logins and do Bulk Action > Share to add them all to one or more collections.

**Comment by kspearrin** [comment]
This is planned, though bulk sharing will not be possible if the login has attachments. Those will still have to be done one at a time due to the complexity behind transactionalizing those operations.

**Comment by Beritknight** [comment]
Would love this. Coming across from LastPass at the moment and currently have on folder with all the logins that I share with my wife in it. It's about 20 logins, and I'm in two bitwarden orgs (Team for work and free for home) so each login I want to share I click share on it, then select the home org from the drop-down, then tick the collection to share into, then click OK.

Share as a bulk action would help a lot. Being able to share a folder into a collection, so that any logins I add to that folder in the future are auto-shared, that would be even better.

**Comment by kspearrin** [comment]
Just a FYI as a workaround for now, if you need to move a ton of logins into a org you can do an import into the org using a CSV. ref: https://help.bitwarden.com/article/import-data/#generic-csv-format-organization-account

**Comment by coryrwest** [comment]
This is the one thing that is lacking for me that would make using bitwarden significantly smoother.

**Comment by kspearrin** [comment]
We are moving away from tracking Bitwarden feature requests like this one as GitHub issues. We have created a [Bitwarden Community Forum](https://community.bitwarden.com) which has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests). Please [sign up on our forums](https://community.bitwarden.com/signup) if you want to continue contributing to feature requests.

Since this was a popular feature request we have already re-created it on the forums and linked back to this GitHub issue for reference. You can vote for this feature request there if you'd like.

https://community.bitwarden.com/t/bulk-share-items/181

This issue will now be closed. Thanks!
